import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DynamicProvider from "@/context/dynamic-provider";
import { StarknetProvider } from "@/context/starknet-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en">
			<body className={inter.className}>
				<DynamicProvider>
					<StarknetProvider>
            {children}
          </StarknetProvider>
				</DynamicProvider>
			</body>
		</html>
	);
}
